### ISSUE TITLE
Add EDA design files

### ISSUE THREAD

**Issue by Redherring32** [Andr-Zero/X-RTC#1]
The original self claimed intent of the OXC-LPCorrectr was to be open hardware. 
Per the definition of open source the EDA software design files should be supplied. (E.g KiCad .kicad_pcb .kicad_sch and .kicad_pro files)
Gerber files are an output (they do not qualify for the definition of a source file, they're as close to source files as an EXE), and do not preserve the original documentation (schematic, editable layout, netlists, and net names) and therefore prevent anyone from contributing. 

Admittedly the original project also doesn't properly do so either, but that doesn't stop this oversight from being corrected here. If you need any help with this just let me know. 

Thanks. 
-Red

**Comment by MrMilenko** [comment]
When is MakeMHz going to release the KiCad files for the Xbox HD+ that they’ve been saying will be coming in the near future for the last 3 years?

Why is it that whenever someone outside of your group does anything, you guys flock to it with some kind of gotcha and make demands like this, but force pushing to fix two year old typos and releasing binary blobs as opensource is perfectly acceptable elsewhere?

![IMG_4321](https://github.com/user-attachments/assets/0c16bbd3-2e4e-44c6-ae44-f043e710025e)

**Comment by JizzyRivers** [comment]
painschamp

**Comment by Andr-Zero** [comment]
Alright... A couple musings, then I'm closing this. 
1) To clarify the license, CERN-OHL-S v2 or later. The missing details in the readme and files needed to comply will be uploaded shortly with a revised gerbers, if not already.
2) One could argue comparing a gerber to a compiled executable is an error. They are indeed the source used for the production of a product. In a common format that most, if not all software can understand and import. In fact, this is how I imported Kekule's OXC-LPCorrectr into my project file. I often see other OSHW with only gerbers released. 
3) Definition 1.8, " 'Complete Source' means the set of all Source necessary to Make a Product..." Since the PCB is a product, I see just the gerbers sufficient here.
4) In a partial contradiction of 3, yet partly affirming of 2 & 3. "...in the preferred form for making modifications..." What is “preferred”? Native EDA files? Well sure. For every EDA software out there? That seems silly… But that might be “preferred” by someone using a different EDA. Could just export as gerbers as that almost universal. Again, that’s how I imported the existing OXC-LPCorrectr design. However, that’s far from ideal for a much more complex design. I say “Preferred” is too ambiguous…
5) @MrMilenko, seeing that years ago is why I bought several in support of the designer. Seeing how nothing came from that I do feel taken advantage of, now regret that decision.

Regardless if my musings are accurate or not. It’s late at night and I really care either way. I will release the KiCAD files I have, I feel that is in the spirt of being Open Sourced. I think I took all the none related information out, like my grocery list from a few weeks ago… There are no schematics, as there was not a need for one. Otherwise I would include those as well. To the best of my current sleep deprived state, I believe I have all the necessary things in place for the OSHW license. If not, please contact my directly if you so feel.
